create table role (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  label VARCHAR(255) NOT NULL
);
create table size (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  label VARCHAR(255) NOT NULL
);
create table type (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  label VARCHAR(255) NOT NULL
);

create table season (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  label VARCHAR(255) NOT NULL
);

CREATE TABLE product (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  description TEXT NOT NULL,
  img_front VARCHAR(255) NOT NULL,
  img_back VARCHAR(255) NOT NULL,
  img_zoom VARCHAR(255) NULL,
  type_id INT,
  CONSTRAINT fk_product_by_type FOREIGN KEY (type_id) REFERENCES type(id) ON DELETE CASCADE,
  season_id INT,
  CONSTRAINT fk_product_by_season FOREIGN KEY (season_id) REFERENCES season(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE size_by_product (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    quantity INT NOT NULL,
  size_id INT,
  product_id INT,
  FOREIGN KEY (size_id) REFERENCES size(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);

create table customer (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  firstname VARCHAR(255) NULL,
  lastname VARCHAR(255) NULL,
  email VARCHAR(255) NOT NULL unique,
  password VARCHAR(255) NOT NULL,
  role_id INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
);
